/**
 * Builds the single bash provisioning script executed on the Lightsail box
 * (uploaded via scp, run with sudo). It is a faithful automation of
 * docs/DEPLOYMENT.md §2b: packages, Postgres, clone, .env, migrations,
 * systemd, admin build, nginx, certbot.
 */

/** Compose the API .env file content from collected answers. */
export function buildApiEnv(cfg) {
  const lines = [
    'PORT=4000',
    `DATABASE_URL=postgres://pothole:${cfg.pgPassword}@localhost:5432/potholes`,
    `AUTH0_DOMAIN=${cfg.auth0Domain}`,
    `AUTH0_AUDIENCE=${cfg.auth0Audience}`,
    `RESEND_API_KEY=${cfg.resendApiKey ?? ''}`,
    `MAIL_FROM=${cfg.mailFrom}`,
    `ADMIN_EMAIL=${cfg.adminEmail}`,
    `CORS_ORIGINS=https://${cfg.adminDomain}`,
  ];
  if (cfg.storageChoice === 's3') {
    lines.push(
      'STORAGE_DRIVER=s3',
      'STORAGE_DIR=/var/lib/pothole/uploads', // chunk staging stays local
      `S3_BUCKET=${cfg.s3Bucket}`,
      `S3_REGION=${cfg.s3Region}`,
      `AWS_ACCESS_KEY_ID=${cfg.s3AccessKeyId}`,
      `AWS_SECRET_ACCESS_KEY=${cfg.s3SecretAccessKey}`,
    );
    if (cfg.s3Endpoint) lines.push(`S3_ENDPOINT=${cfg.s3Endpoint}`);
  } else {
    lines.push('STORAGE_DRIVER=local', 'STORAGE_DIR=/var/lib/pothole/uploads');
  }
  lines.push('OSRM_DATA_DIR=/var/lib/pothole/osrm');
  return lines.join('\n') + '\n';
}

/** Admin dashboard build-time env. */
export function buildAdminEnv(cfg) {
  return [
    `VITE_API_URL=https://${cfg.apiDomain}`,
    `VITE_AUTH0_DOMAIN=${cfg.auth0Domain}`,
    `VITE_AUTH0_CLIENT_ID=${cfg.auth0SpaClientId}`,
    `VITE_AUTH0_AUDIENCE=${cfg.auth0Audience}`,
  ].join('\n') + '\n';
}

/** Nginx site config (verbatim from the guide, domains substituted). */
export function buildNginxConfig(cfg) {
  return `server {
    listen 80;
    server_name ${cfg.apiDomain};
    # 1 GB videos + slow uploads:
    client_max_body_size 1100m;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    location / { proxy_pass http://127.0.0.1:4000;
                 proxy_set_header Host $host;
                 proxy_set_header X-Forwarded-For $remote_addr; }
}
server {
    listen 80;
    server_name ${cfg.adminDomain};
    root /opt/pothole/apps/admin/dist;
    location / { try_files $uri /index.html; }   # SPA fallback
}
`;
}

const SYSTEMD_UNIT = `[Unit]
Description=PotholeCollect API
After=network.target postgresql.service

[Service]
User=ubuntu
WorkingDirectory=/opt/pothole/apps/api
ExecStart=/usr/bin/npm run start
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
`;

/**
 * The full provisioning script. Runs as root (sudo bash). All values are
 * baked in literally; user-facing files use quoted heredocs so nothing is
 * shell-expanded on the server.
 */
export function buildProvisionScript(cfg) {
  const dockerBlock = cfg.installDocker
    ? `echo "==> Docker (for the OSRM admin panel)"
curl -fsSL https://get.docker.com | sh
usermod -aG docker ubuntu`
    : `echo "==> Skipping Docker (OSRM panel disabled; re-run get.docker.com later if needed)"`;

  return `#!/usr/bin/env bash
# PotholeCollect server provisioning — generated by tools/deploy
# Automates docs/DEPLOYMENT.md §2b on Ubuntu 24.04. Run as root.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

echo "==> apt update/upgrade"
apt-get update -y
apt-get -y upgrade

echo "==> Node 20 (nodesource)"
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get -y install nodejs git nginx certbot python3-certbot-nginx

${dockerBlock}

echo "==> PostgreSQL 16"
apt-get -y install postgresql-16 || apt-get -y install postgresql
systemctl enable --now postgresql
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='pothole'" | grep -q 1 || \\
  sudo -u postgres psql -c "CREATE USER pothole WITH PASSWORD '${cfg.pgPassword}';"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='potholes'" | grep -q 1 || \\
  sudo -u postgres psql -c "CREATE DATABASE potholes OWNER pothole;"

echo "==> Directories"
mkdir -p /opt/pothole /var/lib/pothole/uploads /var/lib/pothole/osrm
chown -R ubuntu /opt/pothole /var/lib/pothole

echo "==> Clone + install"
if [ ! -d /opt/pothole/.git ]; then
  sudo -u ubuntu -H git clone ${JSON.stringify(cfg.repoUrl)} /opt/pothole
else
  # Re-runs must pick up fixes pushed since the first attempt.
  sudo -u ubuntu -H git -C /opt/pothole pull --ff-only || true
fi
cd /opt/pothole
# Lockfile-faithful, from-scratch install: a previously broken tree must
# never poison this run.
sudo -u ubuntu -H rm -rf node_modules apps/api/node_modules packages/shared/node_modules
sudo -u ubuntu -H npm install

echo "==> API .env"
cat > /opt/pothole/apps/api/.env <<'POTHOLE_ENV_EOF'
${buildApiEnv(cfg)}POTHOLE_ENV_EOF
chown ubuntu /opt/pothole/apps/api/.env
chmod 600 /opt/pothole/apps/api/.env

echo "==> Migrations"
sudo -u ubuntu -H npm run migrate --workspace apps/api

echo "==> systemd service"
cat > /etc/systemd/system/pothole-api.service <<'POTHOLE_UNIT_EOF'
${SYSTEMD_UNIT}POTHOLE_UNIT_EOF
systemctl daemon-reload
systemctl enable --now pothole-api

echo "==> Health check"
sleep 5
HEALTH=$(curl -sf --max-time 20 localhost:4000/api/v1/health || true)
echo "health: $HEALTH"
if ! echo "$HEALTH" | grep -q '"ok":true'; then
  echo "!! API health check FAILED — recent logs:" >&2
  journalctl -u pothole-api -n 40 --no-pager >&2 || true
  exit 1
fi

echo "==> Admin dashboard build"
cat > /opt/pothole/apps/admin/.env.production <<'POTHOLE_ADMIN_EOF'
${buildAdminEnv(cfg)}POTHOLE_ADMIN_EOF
chown ubuntu /opt/pothole/apps/admin/.env.production
sudo -u ubuntu -H bash -c 'cd /opt/pothole/apps/admin && npm run build'

echo "==> nginx"
cat > /etc/nginx/sites-available/pothole <<'POTHOLE_NGINX_EOF'
${buildNginxConfig(cfg)}POTHOLE_NGINX_EOF
ln -sf /etc/nginx/sites-available/pothole /etc/nginx/sites-enabled/pothole
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

echo "==> TLS (Let's Encrypt)"
certbot --nginx --non-interactive --agree-tos -m ${JSON.stringify(cfg.leEmail)} \\
  -d ${cfg.apiDomain} -d ${cfg.adminDomain} --redirect

echo "==> Certbot auto-renew verification (non-fatal)"
systemctl list-timers certbot.timer --no-pager || true
if certbot renew --dry-run; then
  echo "renewal dry-run OK"
else
  echo "WARN: certbot renew --dry-run failed — check 'systemctl status certbot.timer' later" >&2
fi

echo "==> DONE. API + admin are live."
`;
}
